# Site settings
title: Xiaohan Yan
#email: xy257@cornell.edu
#description: > # this means to ignore newlines until "baseurl:"
#  Xiaohan Yan, Data Scientist & Statistician
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yanxht.github.io" # the base hostname & protocol for your site
#github_username:  yanxht

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""