# Site settings
title: Xiaohan Yan
email: xy257@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a Data Scientist and Statistician working at Microsoft Azure. 
  Topics on my site include my research and professional development.
url: "https://yanxht.github.io" # the base hostname & protocol for your site
github_username:  yanxht
google_scholar_id: M3uIYO4AAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Data Scientist"
excerpt_separator: "<!--more-->"

exclude:
- README.md

safe: true
lsi: false
